//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.03 at 03:32:55 PM ICT 
//
package hunglnv.entity;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Bulb complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="Bulb">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bulbID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="bulbName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="imgLink" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="wattage" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="luminious" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@Entity
@Table(name = "Bulb")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Bulb", propOrder = { //    "bulbID",
//    "bulbName",
//    "imgLink",
//    "link",
//    "wattage",
//    "luminious",
//    "price"
})
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Bulb.findAll", query = "SELECT b FROM Bulb b")
    , @NamedQuery(name = "Bulb.findByBulbID", query = "SELECT b FROM Bulb b WHERE b.bulbID = :bulbID")
    , @NamedQuery(name = "Bulb.findByBulbName", query = "SELECT b FROM Bulb b WHERE b.bulbName = :bulbName")
    , @NamedQuery(name = "Bulb.findByImgLink", query = "SELECT b FROM Bulb b WHERE b.imgLink = :imgLink")
    , @NamedQuery(name = "Bulb.findByLink", query = "SELECT b FROM Bulb b WHERE b.link = :link")
    , @NamedQuery(name = "Bulb.findByWattage", query = "SELECT b FROM Bulb b WHERE b.wattage = :wattage")
    , @NamedQuery(name = "Bulb.findByLuminous", query = "SELECT b FROM Bulb b WHERE b.luminous = :luminous")
    , @NamedQuery(name = "Bulb.findByPrice", query = "SELECT b FROM Bulb b WHERE b.price = :price")})
public class Bulb implements Serializable {

    @Id
    @Basic(optional = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "BulbID", nullable = false)
    protected int bulbID;

    @XmlElement(required = true)
    @Column(name = "BulbName", length = 200)
    protected String bulbName;

    @Column(name = "ImgLink", length = 200)
    @XmlElement(required = true)
    protected String imgLink;

    @Column(name = "Link", length = 200)
    @XmlElement(required = true)
    protected String link;

    @XmlElement(required = true)
    @Column(name = "Wattage")
    protected int wattage;

    @XmlElement(required = true)
    @Column(name = "Luminous")
    protected int luminous;

    @XmlElement(required = true)
    @Column(name = "Price")
    protected int price;

    /**
     * Gets the value of the bulbID property.
     *
     * @return 
     */
    public int getBulbID() {
        return bulbID;
    }

    /**
     * Sets the value of the bulbID property.
     *
     * @param value
     */
    public void setBulbID(int value) {
        this.bulbID = value;
    }

    /**
     * Gets the value of the bulbName property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBulbName() {
        return bulbName;
    }

    /**
     * Sets the value of the bulbName property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setBulbName(String value) {
        this.bulbName = value;
    }

    /**
     * Gets the value of the imgLink property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getImgLink() {
        return imgLink;
    }

    /**
     * Sets the value of the imgLink property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setImgLink(String value) {
        this.imgLink = value;
    }

    /**
     * Gets the value of the link property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setLink(String value) {
        this.link = value;
    }

    /**
     * Gets the value of the wattage property.
     *
     * @return 
     */
    public int getWattage() {
        return wattage;
    }

    /**
     * Sets the value of the wattage property.
     *
     * @param value
     */
    public void setWattage(int value) {
        this.wattage = value;
    }

    /**
     * Gets the value of the luminous property.
     *
     * @return 
     */
    public int getLuminous() {
        return luminous;
    }

    /**
     * Sets the value of the luminous property.
     *
     * @param value
     */
    public void setLuminous(int value) {
        this.luminous = value;
    }

    /**
     * Gets the value of the price property.
     *
     */
    public int getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     *
     * @param value
     */
    public void setPrice(int value) {
        this.price = value;
    }

}
