//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.03 at 03:32:55 PM ICT 
//
package hunglnv.object;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Bulb complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="Bulb">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bulbID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="bulbName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="imgLink" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="wattage" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="luminious" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@Entity
@Table(name = "TempaState")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TempaState", propOrder = { //    "bulbID",
//    "bulbName",
//    "imgLink",
//    "link",
//    "wattage",
//    "luminious",
//    "price"
})
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "TempaState.findAll", query = "SELECT t FROM TempaState t")
    , @NamedQuery(name = "TempaState.findByStateID", query = "SELECT t FROM TempaState t WHERE t.stateID = :stateID")
    , @NamedQuery(name = "TempaState.findByStateName", query = "SELECT t FROM TempaState t WHERE t.stateName = :stateName")
    , @NamedQuery(name = "TempaState.findByStateNameAndSeason", query = "SELECT t FROM TempaState t WHERE t.stateName = :stateName AND t.season = :season")
    , @NamedQuery(name = "TempaState.findByTemparature", query = "SELECT t FROM TempaState t WHERE t.temparature = :temparature")
    , @NamedQuery(name = "TempaState.findBySeason", query = "SELECT t FROM TempaState t WHERE t.season = :season")})
public class TempaState implements Serializable {

    @Id
    @Basic(optional = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "StateID", nullable = false)
    protected int stateID;

    @XmlElement(required = true)
    @Column(name = "StateName")
    private String stateName;

    @XmlElement(required = true)
    @Column(name = "Temparature")
    private float temparature;

    @XmlElement(required = true)
    @Column(name = "Season")
    private String season;
    
    public int getStateID() {
        return stateID;
    }

    public void setStateID(int stateID) {
        this.stateID = stateID;
    }

    public String getStateName() {
        return stateName;
    }

    public void setStateName(String stateName) {
        this.stateName = stateName;
    }

    public float getTemparature() {
        return temparature;
    }

    public void setTemparature(float temparature) {
        this.temparature = temparature;
    }

    public String getSeason() {
        return season;
    }

    public void setSeason(String season) {
        this.season = season;
    }

}
